import random
"""
Create a program that will play the “cows and bulls” game with the user. The
game works like this:

Randomly generate a 4-digit number. Ask the user to guess a 4-digit number.
For every digit that the user guessed correctly in the correct place, they
have a “cow”. For every digit the user guessed correctly in the wrong place
is a “bull.” Every time the user makes a guess, tell them how many “cows”
and “bulls” they have. Once the user guesses the correct number, the game is
over. Keep track of the number of guesses the user makes throughout teh game
and tell the user at the end.

Say the number generated by the computer is 1038. An example interaction
could look like this:

  Welcome to the Cows and Bulls Game!
  Enter a number:
   1234
  2 cows, 0 bulls
   1256
  1 cow, 1 bull
  ...
Until the user guesses the number.

"""

random_number = random.randint(1000, 9999)
print("Randomly generated number is", random_number)


def cow_and_bull(user_input):
    counter = 0
    cows = 0
    bulls = 0
    while counter < len(user_input):
        if user_input[counter] in str(random_number):
            if user_input[counter] == str(random_number)[counter]:
                cows = cows + 1
        else:
            bulls = bulls + 1
        counter += 1
    print(cows, "cows, ", bulls, "bulls")


if __name__ == "__main__":
    user_guess = input("Welcome to the Cows and Bulls Game! Enter a 4 - "
                       "digit number: ")
    cow_and_bull(user_guess)
